---
- name: Apply Kubernetes manifest
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy manifest to remote host
      ansible.builtin.copy:
        src: "./ip-locator.yml"
        dest: "/tmp/ip-locator.yml"
        mode: '0644'

    - name: Apply manifest
      shell: |
          kubectl apply -f /tmp/ip-locator.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf